# Generated by Django 3.1 on 2021-07-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
